#!/usr/bin/env python3
"""Generate corpus-results.md from an existing corpus-results.json.

This is a lightweight alternative to re-running diff_results.py when
only the markdown needs to be regenerated (e.g. after patching variant
stats or merging include-gated results). It reads the JSON that
diff_results.py already produced and generates the markdown from it.

Usage:
    python3 bench/corpus/gen_corpus_md.py \
        --input corpus-results.json \
        --output corpus-results.md \
        --style-variant-results style-variant-results.json
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path


def fmt_pct(rate: float) -> str:
    return f"{math.floor(rate * 1000) / 10:.1f}%"


def fmt_pct_precise(rate: float) -> str:
    """Two-decimal match rate, floored: 0.99829 -> '99.82%'."""
    return f"{math.floor(rate * 10000) / 100:.2f}%"


def _sanitize_for_md(s: str) -> str:
    return "".join(
        repr(c)[1:-1] if ord(c) < 0x20 and c not in '\n\t' else c
        for c in s
    )


def _format_example_md(ex) -> str:
    if isinstance(ex, dict):
        loc = ex.get("loc", "")
        msg = ex.get("msg", "")
        msg = _sanitize_for_md(msg)
        return f"{loc}  [{msg}]" if msg else loc
    return _sanitize_for_md(ex)


def _emit_examples(md: list[str], fp_list: list, fn_list: list, limit: int) -> None:
    """Append FP/FN example bullets to *md*."""
    if fp_list:
        for ex in fp_list[:limit]:
            md.append(f"- FP: `{_format_example_md(ex)}`")
        if len(fp_list) > limit:
            md.append(f"- ... and {len(fp_list) - limit:,} more FP")
    if fn_list:
        for ex in fn_list[:limit]:
            md.append(f"- FN: `{_format_example_md(ex)}`")
        if len(fn_list) > limit:
            md.append(f"- ... and {len(fn_list) - limit:,} more FN")
    md.append("")


def generate_md(data: dict, variant_by_cop: dict[str, list[dict]]) -> str:
    """Generate corpus markdown from pre-computed JSON data."""
    summary = data["summary"]
    by_cop = data["by_cop"]
    by_department = data["by_department"]
    repo_results = data.get("by_repo", [])
    by_repo_cop = data.get("by_repo_cop", {})

    total_matches = summary["matches"]
    total_fp = summary["fp"]
    total_fn = summary["fn"]
    oracle_total = total_matches + total_fp + total_fn
    overall_rate = summary.get("overall_match_rate", total_matches / oracle_total if oracle_total > 0 else 1.0)
    repos_perfect = summary.get("repos_perfect", 0)
    repos_error = summary.get("repos_error", 0)
    registered_cops = summary.get("registered_cops", len(by_cop))
    perfect_cops = summary.get("perfect_cops", 0)
    diverging_cops_count = summary.get("diverging_cops", 0)
    inactive_cops = summary.get("inactive_cops", 0)
    total_files = summary.get("total_files_inspected", 0)
    total_files_dropped = summary.get("rubocop_files_dropped", 0)
    all_ids_count = summary.get("total_repos", 0)
    warning_repos = [r for r in repo_results if r.get("rubocop_files_dropped", 0) > 0]

    # Variant totals
    variant_total_matches = total_matches
    variant_total_fp = total_fp
    variant_total_fn = total_fn
    variant_dept_stats: dict[str, dict[str, int]] = {}
    for cop_name, variants in variant_by_cop.items():
        dept = cop_name.split("/")[0]
        if dept not in variant_dept_stats:
            variant_dept_stats[dept] = {"matches": 0, "fp": 0, "fn": 0}
        for v in variants:
            variant_total_matches += v["matches"]
            variant_total_fp += v["fp"]
            variant_total_fn += v["fn"]
            variant_dept_stats[dept]["matches"] += v["matches"]
            variant_dept_stats[dept]["fp"] += v["fp"]
            variant_dept_stats[dept]["fn"] += v["fn"]
    variant_oracle_total = variant_total_matches + variant_total_fp + variant_total_fn
    variant_overall_rate = variant_total_matches / variant_oracle_total if variant_oracle_total > 0 else 1.0

    md = []
    md.append("# Corpus Oracle Results")
    md.append("")
    md.append("> Auto-generated by the [corpus oracle workflow](../.github/workflows/corpus-oracle.yml).")
    md.append(f"> Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")
    md.append("")
    md.append(f"Compares nitrocop against RuboCop on {all_ids_count:,} open-source Ruby repos.")
    md.append("Every offense is compared by file path, line number, and cop name.")
    md.append("")

    md.append("## Summary")
    md.append("")
    md.append("| Metric | Value |")
    md.append("|--------|------:|")
    md.append(f"| Repos | {all_ids_count} |")
    md.append(f"| Repos with 100% match | {repos_perfect} |")
    md.append(f"| Files inspected | {total_files:,} |")
    md.append(f"| Offenses compared | {oracle_total:,} |")
    md.append(f"| Matches (both agree) | {total_matches:,} |")
    md.append(f"| FP (nitrocop extra) | {total_fp:,} |")
    md.append(f"| FN (nitrocop missing) | {total_fn:,} |")
    md.append(f"| Registered cops | {registered_cops:,} |")
    md.append(f"| Cops with exact match | {perfect_cops:,} |")
    md.append(f"| Cops with divergence | {diverging_cops_count:,} |")
    md.append(f"| Cops with no corpus data | {inactive_cops:,} |")
    md.append(f"| **Match rate (default config)** | **{fmt_pct_precise(overall_rate)}** |")
    if variant_by_cop:
        md.append(f"| **Match rate (all variants)** | **{fmt_pct_precise(variant_overall_rate)}** |")
    if repos_error > 0 or warning_repos:
        md.append(f"| Repos with errors | {repos_error} |")
    if warning_repos:
        md.append(f"| Repos with RuboCop parser crashes | {len(warning_repos)} |")
        md.append(f"| RuboCop files dropped (parser crash) | {total_files_dropped:,} |")
    md.append("")

    # Department breakdown (default config)
    if by_department:
        md.append("## Department Breakdown")
        md.append("")
        md.append("### Default Config")
        md.append("")
        md.append("Results using each cop's default RuboCop configuration.")
        md.append("")
        md.append("| Department | Total cops | Exact match | Diverging | No corpus data | Matches | FP | FN | Match % |")
        md.append("|------------|-----------:|------------:|----------:|---------------:|--------:|---:|---:|--------:|")
        for d in by_department:
            total = d["matches"] + d["fp"] + d["fn"]
            pct = fmt_pct(d['match_rate']) if total > 0 else "N/A"
            md.append(
                f"| {d['department']} | {d['cops']:,} | "
                f"{d['perfect_cops']:,} | {d['diverging_cops']:,} | {d['inactive_cops']:,} | "
                f"{d['matches']:,} | {d['fp']:,} | {d['fn']:,} | {pct} |"
            )
        md.append("")

    # Department breakdown (all variants)
    if by_department and variant_by_cop:
        md.append("### All `EnforcedStyle` Variants")
        md.append("")
        md.append("Results combining default config and every non-default `EnforcedStyle` option.")
        md.append("")
        md.append("| Department | Total cops | Exact match | Diverging | No corpus data | Matches | FP | FN | Match % |")
        md.append("|------------|-----------:|------------:|----------:|---------------:|--------:|---:|---:|--------:|")
        for d in by_department:
            vd = variant_dept_stats.get(d["department"], {"matches": 0, "fp": 0, "fn": 0})
            combined_matches = d["matches"] + vd["matches"]
            combined_fp = d["fp"] + vd["fp"]
            combined_fn = d["fn"] + vd["fn"]
            combined_total = combined_matches + combined_fp + combined_fn
            # Count cops diverging in variants but not in default
            default_diverging_names = {c["cop"] for c in by_cop if c.get("diverging") and c["cop"].startswith(d["department"] + "/")}
            variant_only_count = sum(
                1 for cop_name, variants in variant_by_cop.items()
                if cop_name.startswith(d["department"] + "/")
                and cop_name not in default_diverging_names
                and any(v["fp"] + v["fn"] > 0 for v in variants)
            )
            combined_diverging = d["diverging_cops"] + variant_only_count
            combined_pct = fmt_pct(combined_matches / combined_total) if combined_total > 0 else "N/A"
            md.append(
                f"| {d['department']} | {d['cops']:,} | "
                f"{d['perfect_cops'] - variant_only_count:,} | {combined_diverging:,} | {d['inactive_cops']:,} | "
                f"{combined_matches:,} | {combined_fp:,} | {combined_fn:,} | {combined_pct} |"
            )
        md.append("")

    # Diverging cops
    ok_repos = [r for r in repo_results if r.get("status") == "ok"]
    err_repos = [r for r in repo_results if r.get("status") != "ok"]

    # Top divergence contributors
    multi_repo = all_ids_count > 1
    if multi_repo and by_repo_cop:
        repo_diverging_cops: dict[str, int] = {}
        repo_fp_cops: dict[str, int] = {}
        repo_fn_cops: dict[str, int] = {}
        for repo_id_key, cops in by_repo_cop.items():
            fp_cops = sum(1 for c in cops.values() if c.get("fp", 0) > 0)
            fn_cops = sum(1 for c in cops.values() if c.get("fn", 0) > 0)
            diverging = sum(1 for c in cops.values() if c.get("fp", 0) + c.get("fn", 0) > 0)
            if diverging > 0:
                repo_diverging_cops[repo_id_key] = diverging
                repo_fp_cops[repo_id_key] = fp_cops
                repo_fn_cops[repo_id_key] = fn_cops

        if repo_diverging_cops:
            top = sorted(repo_diverging_cops.items(), key=lambda x: x[1], reverse=True)[:20]
            md.append("## Top Divergence Contributors (repos with most diverging cops)")
            md.append("")
            md.append("| Repo | Diverging Cops | FP Cops | FN Cops | Total FP | Total FN |")
            md.append("|------|---------------:|--------:|--------:|---------:|---------:|")
            for repo_id_key, div_count in top:
                r = next((x for x in ok_repos if x["repo"] == repo_id_key), None)
                total_fp_count = r["fp"] if r else 0
                total_fn_count = r["fn"] if r else 0
                md.append(
                    f"| {repo_id_key} | {div_count} | "
                    f"{repo_fp_cops.get(repo_id_key, 0)} | {repo_fn_cops.get(repo_id_key, 0)} | "
                    f"{total_fp_count:,} | {total_fn_count:,} |"
                )
            md.append("")

    # RuboCop warnings
    warn_and_err = warning_repos + err_repos
    if warn_and_err:
        md.append("## RuboCop Warnings")
        md.append("")
        md.append(f"{len(warn_and_err)} repos had RuboCop issues (parser crashes or errors).")
        md.append("")
        md.append("| Repo | Issue | Files Dropped | Error |")
        md.append("|------|-------|--------------|-------|")
        for r in warning_repos:
            dropped = r.get("rubocop_files_dropped", 0)
            err = r.get("rubocop_error", "")
            err_cell = f"`{err}`" if err else ""
            md.append(f"| {r['repo']} | parser crash | {dropped:,} | {err_cell} |")
        for r in err_repos:
            err = r.get("error_message", "")
            err_cell = f"`{err}`" if err else ""
            md.append(f"| {r['repo']} | {r['status']} | all | {err_cell} |")
        md.append("")

    # Diverging cops with variant rows
    diverging = [c for c in by_cop if c.get("diverging")]
    perfect_cop_list = [c for c in by_cop if c.get("perfect_match")]

    variant_only_diverging = []
    if variant_by_cop:
        default_diverging_names = {c["cop"] for c in diverging}
        for cop_name, variants in sorted(variant_by_cop.items()):
            if cop_name not in default_diverging_names:
                if any(v["fp"] + v["fn"] > 0 for v in variants):
                    cop_entry = next((c for c in by_cop if c["cop"] == cop_name), None)
                    if cop_entry:
                        variant_only_diverging.append(cop_entry)

    all_diverging = diverging + variant_only_diverging
    if all_diverging:
        md.append("## Diverging Cops")
        md.append("")
        md.append(
            f"{len(diverging)} cops diverge from RuboCop on the corpus (default config). "
            f"{len(perfect_cop_list)} cops match RuboCop exactly. "
            f"{inactive_cops} cops have no corpus data."
        )
        if variant_only_diverging:
            md.append(
                f" {len(variant_only_diverging)} additional cops diverge only in non-default style variants."
            )
        md.append("")
        md.append("| Cop | Matches | FP | FN | Match % |")
        md.append("|-----|--------:|---:|---:|--------:|")
        for c in diverging:
            total = c["matches"] + c["fp"] + c["fn"]
            pct = fmt_pct(c['match_rate']) if total > 0 else "N/A"
            if c["cop"] in variant_by_cop:
                md.append(f"| {c['cop']} (default) | {c['matches']:,} | {c['fp']:,} | {c['fn']:,} | {pct} |")
                for v in variant_by_cop[c["cop"]]:
                    v_total = v["matches"] + v["fp"] + v["fn"]
                    if v_total == 0:
                        continue
                    v_pct = fmt_pct(v["matches"] / v_total)
                    md.append(f"| ↳ {c['cop']} ({v['style_label']}) | {v['matches']:,} | {v['fp']:,} | {v['fn']:,} | {v_pct} |")
            else:
                md.append(f"| {c['cop']} | {c['matches']:,} | {c['fp']:,} | {c['fn']:,} | {pct} |")

        if variant_only_diverging:
            md.append("")
            md.append("**Variant-only divergence** (perfect in default config, diverge in non-default styles):")
            md.append("")
            md.append("| Cop | Matches | FP | FN | Match % |")
            md.append("|-----|--------:|---:|---:|--------:|")
            for c in sorted(variant_only_diverging, key=lambda x: sum(v["fp"] + v["fn"] for v in variant_by_cop.get(x["cop"], [])), reverse=True):
                total = c["matches"] + c["fp"] + c["fn"]
                pct = fmt_pct(c['match_rate']) if total > 0 else "N/A"
                md.append(f"| {c['cop']} (default) | {c['matches']:,} | {c['fp']:,} | {c['fn']:,} | {pct} |")
                for v in variant_by_cop.get(c["cop"], []):
                    v_total = v["matches"] + v["fp"] + v["fn"]
                    v_pct = fmt_pct(v["matches"] / v_total) if v_total > 0 else "N/A"
                    if v["fp"] + v["fn"] > 0:
                        md.append(f"| ↳ {c['cop']} ({v['style_label']}) | {v['matches']:,} | {v['fp']:,} | {v['fn']:,} | {v_pct} |")
        md.append("")

        # Detail sections — emit <details> for every cop (default + variant-only)
        # that has FP/FN examples, including per-variant examples.
        MD_EXAMPLE_LIMIT = 3
        for c in all_diverging:
            cop_name = c["cop"]
            default_fp = c.get("fp_examples", [])
            default_fn = c.get("fn_examples", [])
            variants = variant_by_cop.get(cop_name, [])
            variant_fp = [ex for v in variants for ex in v.get("fp_examples", [])]
            variant_fn = [ex for v in variants for ex in v.get("fn_examples", [])]
            if not default_fp and not default_fn and not variant_fp and not variant_fn:
                continue
            total = c["matches"] + c["fp"] + c["fn"]
            pct = fmt_pct(c['match_rate']) if total > 0 else "N/A"
            # Aggregate FP/FN across default + variants for the summary line
            all_fp = c["fp"] + sum(v["fp"] for v in variants)
            all_fn = c["fn"] + sum(v["fn"] for v in variants)
            md.append("<details>")
            md.append(f"<summary><strong>{cop_name}</strong> — {c['matches']:,} matches, {all_fp:,} FP, {all_fn:,} FN ({pct})</summary>")
            md.append("")
            if default_fp or default_fn:
                if c["fp"] + c["fn"] > 0:
                    md.append(f"**Default config** ({c['fp']:,} FP, {c['fn']:,} FN):")
                    md.append("")
                    _emit_examples(md, default_fp, default_fn, MD_EXAMPLE_LIMIT)
            for v in variants:
                v_fp = v.get("fp_examples", [])
                v_fn = v.get("fn_examples", [])
                if not v_fp and not v_fn:
                    continue
                md.append(f"**{v['style_label']}** ({v['fp']:,} FP, {v['fn']:,} FN):")
                md.append("")
                _emit_examples(md, v_fp, v_fn, MD_EXAMPLE_LIMIT)
            md.append("</details>")
            md.append("")

    # Per-repo table
    md.append("## Per-Repo Results")
    md.append("")
    md.append(f"{len(ok_repos)} repos completed successfully, {len(err_repos)} had errors.")
    md.append("")
    md.append("| Repo | Files | Match Rate | Matches | FP | FN |")
    md.append("|------|------:|----------:|--------:|---:|---:|")
    for r in sorted(ok_repos, key=lambda x: x.get("match_rate", 0)):
        files = r.get("files_inspected", 0)
        rate = fmt_pct(r['match_rate'])
        md.append(f"| {r['repo']} | {files:,} | {rate} | {r['matches']:,} | {r['fp']:,} | {r['fn']:,} |")
    md.append("")

    if err_repos:
        md.append("<details>")
        md.append(f"<summary>Repos with errors ({len(err_repos)})</summary>")
        md.append("")
        md.append("| Repo | Status | Error |")
        md.append("|------|--------|-------|")
        for r in err_repos:
            err = r.get("error_message", "")
            err_cell = f"`{err}`" if err else ""
            md.append(f"| {r['repo']} | {r['status']} | {err_cell} |")
        md.append("")
        md.append("</details>")
        md.append("")

    # Perfect cops
    if perfect_cop_list:
        md.append("<details>")
        md.append(f"<summary>Perfect cops ({len(perfect_cop_list)} cops with 100% match rate)</summary>")
        md.append("")
        md.append("| Cop | Matches |")
        md.append("|-----|--------:|")
        for c in sorted(perfect_cop_list, key=lambda x: x["matches"], reverse=True):
            md.append(f"| {c['cop']} | {c['matches']:,} |")
        md.append("")
        md.append("</details>")
        md.append("")

    return "\n".join(md) + "\n"


def load_variant_by_cop(path: Path) -> dict[str, list[dict]]:
    """Load variant results into {cop_name: [{style_label, matches, fp, fn}]}."""
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return {}
    result: dict[str, list[dict]] = {}
    for batch in data.get("batches", []):
        for cop_entry in batch.get("by_cop", []):
            cop_name = cop_entry.get("cop", "")
            if cop_name:
                result.setdefault(cop_name, []).append({
                    "style_label": cop_entry.get("style_label", batch.get("name", "?")),
                    "matches": cop_entry.get("matches", 0),
                    "fp": cop_entry.get("fp", 0),
                    "fn": cop_entry.get("fn", 0),
                    "fp_examples": cop_entry.get("fp_examples", []),
                    "fn_examples": cop_entry.get("fn_examples", []),
                })
    return result


def main():
    parser = argparse.ArgumentParser(
        description="Generate corpus-results.md from corpus-results.json")
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--style-variant-results", type=Path, default=None)
    args = parser.parse_args()

    data = json.loads(args.input.read_text())
    variant_by_cop = {}
    if args.style_variant_results:
        variant_by_cop = load_variant_by_cop(args.style_variant_results)

    md = generate_md(data, variant_by_cop)
    args.output.write_text(md)
    print(f"Generated {args.output} ({len(md):,} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
